# Generated by Django 4.0.6 on 2022-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custname', models.CharField(max_length=20)),
                ('custcontact', models.CharField(max_length=20)),
                ('custaddress', models.CharField(max_length=20)),
                ('cashspend', models.CharField(max_length=20)),
                ('prodbought', models.CharField(max_length=500)),
                ('profitsininr', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcat', models.CharField(max_length=20)),
                ('subcat', models.CharField(max_length=20)),
                ('prodname', models.CharField(max_length=20)),
                ('mainuom', models.CharField(max_length=20)),
                ('salesuom', models.CharField(max_length=20)),
                ('contains', models.CharField(max_length=20)),
                ('purchaserate', models.CharField(max_length=20)),
                ('salesrate', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('warnstock', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('tax', models.CharField(max_length=20)),
                ('hsncode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
                ('subcat', models.CharField(max_length=20)),
                ('active', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UOMMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uomname', models.CharField(max_length=10)),
                ('active', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('userfirst', models.BooleanField(default=1)),
                ('companyname', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('gstin', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
