# Generated by Django 4.0.6 on 2022-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompmaster',
            name='isadmin',
            field=models.BooleanField(default=0),
        ),
    ]
