# Generated by Django 4.0.6 on 2022-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OIS', '0002_usercompmaster_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefCatSubcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=20)),
                ('subcat', models.CharField(max_length=20)),
            ],
        ),
    ]
