# Generated by Django 4.0.6 on 2022-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OIS', '0003_defcatsubcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defcatsubcat',
            name='subcat',
            field=models.CharField(max_length=500),
        ),
    ]
